# Generated by Django 4.1.1 on 2022-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChickenFarmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='passW',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
