# Generated by Django 4.1.1 on 2022-12-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChickenFarmApp', '0002_cart_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bought',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
